python:
  - 3.12

occt:
  - 7.8.1

c_compiler:
- vs2022    # [win]
- gcc       # [linux]
- clang     # [osx]
c_stdlib:
- vs        # [win]
- sysroot   # [linux]
- macosx_deployment_target  # [osx]
cxx_compiler:
- vs2022    # [win]
- gcc       # [linux]
- clangxx   # [osx]
c_compiler_version:
- '12'    # [linux]
- '16'    # [osx]
cxx_compiler_version:
- '12'    # [linux]
- '16'    # [osx]
c_stdlib_version:
  - 2.17    # [linux]
  - 10.13   # [osx and x86_64]
  - 11.0    # [osx and arm64]
hdf5:
- 1.14.6
libboost_devel:
- '1.86'
libxml2:
- 2.13
mpfr:
- '4'
gmp:
- '6'  # [not win]
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x

zlib:
- '1'
target_platform:
- win-64    # [win]
- linux-64  # [linux]
- osx-64    # [osx]
macos_machine:                 # [osx]
  - x86_64-apple-darwin13.4.0  # [osx and x86_64]
  - arm64-apple-darwin20.0.0   # [osx and arm64]
MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 11.0                       # [osx and arm64]
  - 10.13                      # [osx and x86_64]

CONDA_BUILD_SYSROOT:  # [osx]
  - "/Users/runner/work/MacOSX10.13.sdk"  # [osx and x86_64]
