name: Deploy Pyodide Demo App to GitHub Pages

permissions:
  id-token: write
  pages: write

on:
  push:
    paths:
      - 'src/pyodide/**'
      - '.github/workflows/publish-pyodide-demo-app.yml'
    branches:
      - v0.8.0

jobs:
  activate:
    runs-on: ubuntu-latest
    if: |
      github.repository == 'IfcOpenShell/IfcOpenShell'
    steps:
    - name: Set env
      run: echo ok go
      
  build:
    needs: activate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (recursive)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: src/pyodide/demo-app/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
